[package]
name = "rust_lib_astral"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.8.0"
lazy_static =  "1.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.19.0"
dashmap = "6.1.0"
chrono = "0.4.38"
humansize = "1.1.1"
tokio = "1.39.2"
anyhow = "1.0.95"
surge-ping = "0.8"
easytier = { path = "./easytier" }
windows = { version = "0.48.0", features = ["Win32_NetworkManagement_WindowsFirewall",
 "Win32_System_Com", 
 "Win32_NetworkManagement_IpHelper",
    "Win32_Networking_WinSock",
    "Win32_System_WindowsProgramming",
    "Win32_Foundation"] }
winapi = { version = "0.3", features = ["iphlpapi", "iptypes", "netioapi", "winerror", "ws2def"] }
rand = "0.9.1"

[build-dependencies]
thunk-rs = { version = "0.3.3", features = ["win7"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
